# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
   🥳 Thank you for your interest in contributing to WHO open source projects. If you've followed our instructions in [README.md](https://github.com/WorldHealthOrganization/open-source-communication-channel#-who-may-use-this) we will reach out to you soon with further instructions! :tada:

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thank you for opening this pull request! We appreciate your contributions! Please check out our [contributing guidelines](https://github.com/WorldHealthOrganization/open-source-communication-channel/blob/main/CONTRIBUTING.md).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! We here at WHO appreciate your time and contribution!

# It is recommended to include as many gifs and emojis as possible!

